---

- name: Crear grupo prometheus
  group:
    name: prometheus
    system: true
    state: present

- name: Crear usuario prometheus
  user:
    name: prometheus
    uid: 800
    group: prometheus
    shell: /bin/false
    system: yes
    createhome: no

- name: Directorio config. prometheus
  file:
    path: "/etc/prometheus"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0770

- name: Directorio datos prometheus
  file:
    path: "/var/lib/prometheus"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755